#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import shutil
import sys
import urllib.request
import zipfile
from pathlib import Path


def _die(message: str, code: int = 1) -> int:
    print(message, file=sys.stderr)
    return code


def _write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def detect_reaper_resource() -> int:
    if os.name == "nt":
        try:
            import winreg

            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\REAPER") as key:
                value, _kind = winreg.QueryValueEx(key, "REAPER_PREF_DIR")
                if value:
                    print(value)
                    return 0
        except OSError:
            pass

    appdata = os.environ.get("APPDATA")
    if appdata:
        print(str(Path(appdata) / "REAPER"))
    else:
        print(str(Path.home() / "AppData" / "Roaming" / "REAPER"))
    return 0


def write_config(argv: list[str]) -> int:
    if len(argv) != 5:
        return _die("write_config requires: config_path projects_dir resource_path port")

    config_path = Path(argv[1])
    projects_dir = argv[2]
    resource_path = argv[3]
    try:
        port = int(argv[4])
    except ValueError:
        return _die("Port must be a number.")
    if not 1 <= port <= 65535:
        return _die("Port must be between 1 and 65535.")

    data = {
        "_comment": "ReaperAI MCP Server 配置文件",
        "reaper_projects_dir": projects_dir,
        "reaper_resource_path": resource_path,
        "server": {"host": "127.0.0.1", "port": port},
    }
    _write_json(config_path, data)
    return 0


def write_config_env(argv: list[str]) -> int:
    if len(argv) != 2:
        return _die("write_config_env requires: config_path")

    config_path = Path(argv[1])
    projects_dir = os.environ.get("REAPERAI_CW_PROJECTS_DIR", "")
    resource_path = os.environ.get("REAPERAI_CW_RESOURCE_PATH", "")
    port_text = os.environ.get("REAPERAI_CW_PORT", "8765")
    return write_config(["write_config", str(config_path), projects_dir, resource_path, port_text])


def write_lua_config(argv: list[str]) -> int:
    if len(argv) != 2:
        return _die("write_lua_config requires: lua_config_path")

    lua_config = Path(argv[1])
    lua_config.parent.mkdir(parents=True, exist_ok=True)
    lua_config.write_text(
        "\n".join(
            [
                "# ReaperAI 配置文件",
                "# Generated by 配置向导.bat",
                "",
                "LLM_API_KEY=在此填入你的 API Key",
                "LLM_API_URL=https://api.openai.com/v1/chat/completions",
                "LLM_MODEL=gpt-4o-mini",
                "",
                "# ELEVENLABS_API_KEY=在此填入 ElevenLabs API Key（可选）",
                "# 获取地址: https://elevenlabs.io/app/settings/api-keys",
                '# 使用方式: 在 ReaperAI 输入框输入 "11你的描述" 即可生成音频',
                "# 例如: 11爆炸音效，低沉有力",
                "# 例如: 11Hello world",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return 0


def download(argv: list[str]) -> int:
    if len(argv) != 3:
        return _die("download requires: url output_path")

    url = argv[1]
    output_path = Path(argv[2])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = output_path.with_name(output_path.name + ".tmp")
    if tmp_path.exists():
        tmp_path.unlink()

    request = urllib.request.Request(url, headers={"User-Agent": "ReaperAI-config-wizard/1.0"})
    with urllib.request.urlopen(request, timeout=180) as response, tmp_path.open("wb") as handle:
        shutil.copyfileobj(response, handle)
    tmp_path.replace(output_path)
    print(str(output_path))
    return 0


def install_ffmpeg(argv: list[str]) -> int:
    if len(argv) != 3:
        return _die("install_ffmpeg requires: zip_path ffmpeg_dir")

    zip_path = Path(argv[1])
    ffmpeg_dir = Path(argv[2])
    if not zip_path.exists():
        return _die(f"FFmpeg zip not found: {zip_path}")

    ffmpeg_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path) as archive:
        names = archive.namelist()
        ffmpeg_entry = None
        for name in names:
            normalized = name.replace("\\", "/")
            if normalized.lower().endswith("/bin/ffmpeg.exe"):
                ffmpeg_entry = normalized
                break
        if not ffmpeg_entry:
            return _die("ffmpeg.exe was not found inside the downloaded zip.")

        root = ffmpeg_entry[: -len("/bin/ffmpeg.exe")]
        for info in archive.infolist():
            normalized = info.filename.replace("\\", "/")
            if not normalized.startswith(root + "/"):
                continue
            relative = normalized[len(root) + 1 :]
            if not relative:
                continue
            top = relative.split("/", 1)[0].lower()
            if top not in {"bin", "doc", "presets"}:
                continue

            target = ffmpeg_dir / Path(relative)
            if info.is_dir() or relative.endswith("/"):
                target.mkdir(parents=True, exist_ok=True)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            with archive.open(info) as src, target.open("wb") as dst:
                shutil.copyfileobj(src, dst)

    ffmpeg_exe = ffmpeg_dir / "bin" / "ffmpeg.exe"
    if not ffmpeg_exe.exists():
        return _die(f"FFmpeg install did not create: {ffmpeg_exe}")
    print(str(ffmpeg_exe))
    return 0


def set_ffmpeg_path(argv: list[str]) -> int:
    if len(argv) != 3:
        return _die("set_ffmpeg_path requires: config_path ffmpeg_exe")

    config_path = Path(argv[1])
    ffmpeg_exe = str(Path(argv[2]))
    data: dict = {}
    if config_path.exists():
        try:
            data = json.loads(config_path.read_text(encoding="utf-8-sig"))
        except json.JSONDecodeError as exc:
            return _die(f"Invalid config JSON: {exc}")
    data["ffmpeg_path"] = ffmpeg_exe
    _write_json(config_path, data)
    return 0


def main() -> int:
    if len(sys.argv) < 2:
        return _die("Missing command.")

    command = sys.argv[1]
    argv = sys.argv[1:]
    if command == "detect_reaper_resource":
        return detect_reaper_resource()
    if command == "write_config":
        return write_config(argv)
    if command == "write_config_env":
        return write_config_env(argv)
    if command == "write_lua_config":
        return write_lua_config(argv)
    if command == "download":
        return download(argv)
    if command == "install_ffmpeg":
        return install_ffmpeg(argv)
    if command == "set_ffmpeg_path":
        return set_ffmpeg_path(argv)
    return _die(f"Unknown command: {command}")


if __name__ == "__main__":
    raise SystemExit(main())
