@echo off
setlocal enabledelayedexpansion
chcp 65001 >nul

:::: 获取脚本所在目录
set "SCRIPT_DIR=%~dp0"
cd /d "%SCRIPT_DIR%"

echo ============================================
echo   ReaperAI v1.0 - 配置向导
echo ============================================
echo.
echo 本向导将帮助你创建 config.json 配置文件
echo.

set "CONFIG_FILE=config.json"

:::: 检查现有配置
if exist "%CONFIG_FILE%" (
    echo [提示] 检测到已有配置文件
    set /p overwrite="是否覆盖? (y/n): "
    if /i "!overwrite!"=="n" (
        echo [取消] 配置未更改
        pause
        exit /b 0
    )
    if /i "!overwrite!"=="y" (
        echo [OK] 将覆盖现有配置...
    ) else (
        echo [错误] 输入无效，默认取消配置
        pause
        exit /b 0
    )
    echo.
)

:::: 询问工程目录
echo [1/4] REAPER 工程扫描目录
echo        设置扫描起点，AI 会在这里搜索所有 .rpp 工程文件
echo        可以是大范围（如 E:/ 扫描整个 E 盘）
echo        或特定文件夹（如 D:/MyProjects/）
echo.
set /p projects_dir="扫描目录 (默认 E:/, 直接回车=全盘): "
if "%projects_dir%"=="" set "projects_dir=E:/"
call :normalize_input_path projects_dir
echo.

:::: 询问 REAPER 资源路径
echo [2/4] REAPER 资源路径
echo        留空会自动检测，或手动输入，例如：
echo        C:/Users/用户名/AppData/Roaming/REAPER
echo.
set /p resource_path="资源路径 (留空=自动检测): "
call :normalize_input_path resource_path
echo.

:::: 询问端口
echo [3/4] 服务器端口
echo        默认 8765，如无冲突建议保持默认
echo.
set /p port="端口号 (默认: 8765): "
if "%port%"=="" set "port=8765"
echo.

:::: 生成配置文件
echo [生成] 正在创建配置文件...
echo.

rem 修复 JSON 中的反斜杠转义：先把 / 换成 \，再把 \ 换成 \\
set "JSON_PROJECTS=%projects_dir%"
set "JSON_PROJECTS=%JSON_PROJECTS:\=\\%"
set "JSON_RESOURCE=%resource_path%"
set "JSON_RESOURCE=%JSON_RESOURCE:\=\\%"

echo {> "%CONFIG_FILE%"
echo   "_comment": "ReaperAI MCP Server 配置文件",>> "%CONFIG_FILE%"
echo   "reaper_projects_dir": "%JSON_PROJECTS%",>> "%CONFIG_FILE%"
echo   "reaper_resource_path": "%JSON_RESOURCE%",>> "%CONFIG_FILE%"
echo   "server": {>> "%CONFIG_FILE%"
echo     "host": "127.0.0.1",>> "%CONFIG_FILE%"
echo     "port": %port%>> "%CONFIG_FILE%"
echo   }>> "%CONFIG_FILE%"
echo }>> "%CONFIG_FILE%"

:: 同时写入 REAPER 资源目录的 TXT 配置文件（供 Lua 读取）
:: 优先使用用户输入的资源路径，否则尝试自动检测
if not "%resource_path%"=="" (
    set "LUA_CONFIG=%resource_path%\ReaperAI_config.txt"
) else (
    rem 尝试从注册表或常见位置检测 REAPER 资源路径
    for /f "tokens=*" %%a in ('powershell -Command "try { $p = Get-ItemProperty -Path 'HKCU:\Software\REAPER' -Name 'REAPER_PREF_DIR' -ErrorAction Stop; return $p.REAPER_PREF_DIR } catch { return $env:APPDATA + '\REAPER' }"') do set "REAPER_RES_PATH=%%a"
    if "!REAPER_RES_PATH!"=="" set "REAPER_RES_PATH=%APPDATA%\REAPER"
    set "LUA_CONFIG=!REAPER_RES_PATH!\ReaperAI_config.txt"
)

:: 确保目标目录存在
for %%F in ("%LUA_CONFIG%") do set "LUA_CONFIG_DIR=%%~dpF"
if not exist "%LUA_CONFIG_DIR%" mkdir "%LUA_CONFIG_DIR%" 2>nul

(
echo # ReaperAI 配置文件
echo #  Generated by 配置向导.bat
echo.
echo LLM_API_KEY=在此填入你的 API Key
echo LLM_API_URL=https://api.openai.com/v1/chat/completions
echo LLM_MODEL=gpt-4o-mini
echo.
echo # ELEVENLABS_API_KEY=在此填入 ElevenLabs API Key（可选）
echo # 获取地址: https://elevenlabs.io/app/settings/api-keys
echo # 使用方式: 在 ReaperAI 输入框输入 "11你的描述" 即可生成音频
echo # 例如: 11爆炸音效，低沉有力
echo # 例如: 11Hello world
) > "%LUA_CONFIG%"

echo [OK] 配置文件已创建: %CONFIG_FILE%
echo [OK] Lua 配置已创建: %LUA_CONFIG%
echo.

:::: FFmpeg 检查和下载
echo [4/4] 检查 FFmpeg...
echo.

set "FFMPEG_DIR=%SCRIPT_DIR%tools\ffmpeg"
set "FFMPEG_EXE=%FFMPEG_DIR%\bin\ffmpeg.exe"

:: 检查是否已有 FFmpeg
if exist "%FFMPEG_EXE%" (
    echo [OK] 检测到已有 FFmpeg: %FFMPEG_EXE%
    goto :ffmpeg_done
)

:: 检查系统 PATH 中是否有 FFmpeg
where ffmpeg >nul 2>&1
if %errorlevel%==0 (
    echo [OK] 检测到系统 FFmpeg
    for /f "tokens=*" %%a in ('where ffmpeg') do (
        echo        路径: %%a
        goto :ffmpeg_done
    )
)

:: 自动下载 FFmpeg
echo [提示] 未检测到 FFmpeg，正在自动下载...
echo        这将用于音频格式转换（如 ElevenLabs 生成的 MP3 转 WAV）
echo.

set "FFMPEG_URL=https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
set "FFMPEG_ZIP=%TEMP%\ffmpeg_essentials.zip"

echo [下载] 正在从官方源下载 FFmpeg...
echo        URL: %FFMPEG_URL%
echo.

:: 使用 PowerShell 下载
powershell -Command "& {$progressPreference='silentlyContinue'; try { Invoke-WebRequest -Uri '%FFMPEG_URL%' -OutFile '%FFMPEG_ZIP%' -TimeoutSec 120 } catch { exit 1 }}"

if not exist "%FFMPEG_ZIP%" (
    echo [失败] 官方源下载失败，尝试备用源...
    set "FFMPEG_URL=https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
    echo [下载] 备用源: %FFMPEG_URL%
    powershell -Command "& {$progressPreference='silentlyContinue'; try { Invoke-WebRequest -Uri '%FFMPEG_URL%' -OutFile '%FFMPEG_ZIP%' -TimeoutSec 120 } catch { exit 1 }}"
)

if not exist "%FFMPEG_ZIP%" (
    echo [错误] FFmpeg 下载失败，请手动安装：
    echo        1. 访问 https://www.gyan.dev/ffmpeg/builds/
    echo        2. 下载 ffmpeg-release-essentials.zip
    echo        3. 解压到 %FFMPEG_DIR%
    echo        4. 确保 bin\ffmpeg.exe 存在
    echo.
    goto :ffmpeg_done
)

echo [解压] 正在解压 FFmpeg...
powershell -Command "& {$progressPreference='silentlyContinue'; Expand-Archive -Path '%FFMPEG_ZIP%' -DestinationPath '%TEMP%\ffmpeg_extract' -Force}"

:: 查找解压后的 ffmpeg.exe
for /d %%D in ("%TEMP%\ffmpeg_extract\ffmpeg-*") do (
    if exist "%%D\bin\ffmpeg.exe" (
        echo [安装] 复制 FFmpeg 到项目目录...
        if not exist "%FFMPEG_DIR%" mkdir "%FFMPEG_DIR%"
        xcopy "%%D\bin" "%FFMPEG_DIR%\bin\" /E /I /Y >nul
        xcopy "%%D\doc" "%FFMPEG_DIR%\doc\" /E /I /Y >nul
        xcopy "%%D\presets" "%FFMPEG_DIR%\presets\" /E /I /Y >nul
        goto :ffmpeg_installed
    )
)

echo [错误] 解压后找不到 ffmpeg.exe
goto :ffmpeg_done

:ffmpeg_installed
echo [OK] FFmpeg 安装完成: %FFMPEG_EXE%

:: 更新 config.json 添加 ffmpeg_path
set "CONFIG_TEMP=%TEMP%\config_temp.json"
powershell -Command "& {$config=Get-Content '%CONFIG_FILE%' -Raw | ConvertFrom-Json; $config.ffmpeg_path='%FFMPEG_EXE:\=\\%'; $config | ConvertTo-Json -Depth 4 | Set-Content '%CONFIG_TEMP%' -Encoding UTF8}"
if exist "%CONFIG_TEMP%" (
    move /Y "%CONFIG_TEMP%" "%CONFIG_FILE%" >nul
    echo [OK] 已更新配置文件中的 FFmpeg 路径
)

:: 清理临时文件
del "%FFMPEG_ZIP%" 2>nul
rmdir /S /Q "%TEMP%\ffmpeg_extract" 2>nul

:ffmpeg_done
echo.

echo ============================================
echo   配置完成!
echo ============================================
echo.
echo 配置内容:
echo   Projects dir: %projects_dir%
echo   Resource path: %resource_path%
echo   端口: %port%
echo.
pause
exit /b 0

:normalize_input_path
set "VAR_NAME=%~1"
if "%VAR_NAME%"=="" exit /b 0
set "RAW_PATH="
call set "RAW_PATH=%%%VAR_NAME%%%"
if not defined RAW_PATH exit /b 0
set "RAW_PATH=!RAW_PATH:"=!"
set "RAW_PATH=!RAW_PATH:/=\!"
if not "!RAW_PATH!"=="" if "!RAW_PATH:~-1!"=="\" if not "!RAW_PATH:~1,2!"==":\" set "RAW_PATH=!RAW_PATH:~0,-1!"
set "%VAR_NAME%=!RAW_PATH!"
exit /b 0
